name: predix-ts-sample
version: "1.0"
summary: "This is Predix Time-Series Sample Application"
description: |
  A Predix Time-Series Sample Applilcation using the golang
  Predix bindings.
confinement: strict

apps:
  predix-ts-hello:
    command: sensor

parts:
  godd:
    plugin: go
    source: .
