name: predix-ts-sample
version: "1.0"
summary: "This is Predix Time-Series Sample Application"
description: |
  A Predix Time-Series Sample Applilcation using the golang
  Predix bindings.
grade: stable
confinement: strict

apps:
  predix-ts-sample:
    command: sensor
    plugs: [network]

parts:
  predix-sensor-demo:
    source: .
    plugin: go
